[project]
name = "mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel Valdés Alonzo", email = "gabriel.valdes.alonzo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "xlrd>=2.0.2",
]

[project.scripts]
mlops = "mlops:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
